root: true
parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint/eslint-plugin'
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:jest/recommended
  - plugin:jest/style
  - prettier
env:
  node: true
  jest: true
rules:
  '@typescript-eslint/interface-name-prefix': off
  '@typescript-eslint/explicit-function-return-type': off
  '@typescript-eslint/explicit-module-boundary-types': off
  '@typescript-eslint/no-explicit-any': off
  '@typescript-eslint/no-unused-vars': error
  jest/expect-expect:
    - error
    - assertFunctionNames: [expect, request.**.expect]
